<?php
namespace Seaf\DI;

class SomeClass {
    public $params;

    public function __construct ($params = array()) {
        $this->params = $params;
    }
}

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-08 at 05:40:48.
 */
class FactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Factory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = Factory::factory(array(
            'classA' => array(
                'definition' => 'Seaf\DI\SomeClass',
                'options' => array(array('key'=>'value'))
            ),
            'classB' => array(
                'definition' => function($n1,$n2,$n3) { return new SomeClass(array('ans'=>$n1*$n2*$n3)); },
                'options' => array(1,2,3)
            )
        ));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Seaf\DI\Factory::create
     * @todo   Implement testCreate().
     */
    public function testCreate()
    {
        $classA = $this->object->create('classA');
        $classB = $this->object->create('classB');

        $this->assertEquals('value', $classA->params['key']);
        $this->assertEquals('6', $classB->params['ans']);
    }
}
