<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-08 at 05:12:41.
 */
class SeafTest extends PHPUnit_Framework_TestCase
{
    /**
     * @covers Seaf::singleton
     * @todo   Implement testSingleton().
     */
    public function testSingleton()
    {
        $this->assertInstanceOf(
            'Seaf',
            Seaf::singleton( )
        );

        $seaf = Seaf::singleton( );

        $this->assertEquals(
            $seaf,
            Seaf::singleton( )
        );
    }
}
