<?php
namespace Seaf\Module\P18n;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-14 at 15:59:35.
 */
class P18nTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var P18n
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new P18n;
        $this->object->register();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Seaf\Module\P18n\P18n::defaultLocale
     */
    public function testDefaultLocale()
    {
        $this->object->defaultLocale('ja');
        $this->assertEquals(
            'ja',
            $this->object->getDefaultLocale()
        );
    }

    /**
     * @covers Seaf\Module\P18n\P18n::locale
     */
    public function testLocale()
    {
        $this->object->locale('ja');
        $this->assertEquals(
            'ja',
            $this->object->getLocale()
        );
    }

    /**
     * @covers Seaf\Module\P18n\P18n::translate
     */
    public function testTranslate()
    {
        $t = $this->object->defaultLocale('ja')->locale('en')->getHelper();

        $this->assertEquals(
            'Seaf -FrameWork-',
            $t('site.title')
        );
        $this->assertTrue(is_array($t('site')));
        $this->assertEquals("日本",$t('onlyjp'));
        $this->assertEquals("私の名前ははじめです",$t('myname','はじめ'));
        $this->assertEquals("日本",$t('onlyjp'));
        $this->assertEquals(
            'なし',
            $t('count_pl', 0)
        );
        $this->assertEquals(
            'ひとつ',
            $t('count_pl', 1)
        );
        $this->assertEquals(
            '2個',
            $t('count_pl', 2)
        );
        $this->assertEquals(
            "[[not.exist.any.where]]",
            $t('not.exist.any.where')
        );
    }
}
