<?php
namespace Seaf\Net\Request;

use Seaf;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-16 at 19:48:59.
 */
class BaseTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Base
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Base();
    }

    /**
     * @covers Seaf\Net\Request\Base::initRequest
     */
    public function testInitializer()
    {
        var_dump(new Base('cli'));
        var_dump(new Base('web'));
    }
}
