<?php
namespace Seaf\Kernel;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-17 at 18:33:28.
 */
class KernelTest extends \PHPUnit_Framework_TestCase
{
    protected function setUp()
    {
        Kernel::init(true);
    }

    protected function tearDown()
    {
    }

    public function testInit()
    {
        Kernel::init(true);
    }

    /**
     * DIを外部から静的に変更するテスト
     */
    public function testDIExtend()
    {
        Kernel::DI()->singleton()->register('test', __NAMESPACE__.'\\Kernel');

        $this->assertEquals(
            get_class(Kernel::DI()->singleton()),
            get_class(Kernel::DI())
        );

        $di = new \Seaf\DI\Container();
        $this->assertFalse($di->has('test'));

        $di = new \Seaf\Kernel\DI\Container();
        $this->assertTrue($di->has('test'));

        $this->assertInstanceOf(
            __NAMESPACE__.'\\Kernel',
            $di->get('test')
        );
    }

    /**
     * DIからAutoLoaderを読み込むテスト
     */
    public function testAutoLoader()
    {
        $this->assertInstanceOf(
            'Seaf\Kernel\Component\AutoLoader',
            Kernel::AutoLoader()
        );
    }

    /**
     * GLOBALSのテスト
     */
    public function testGLOBALS()
    {
        $this->assertInstanceOf(
            'Seaf\Kernel\Component\Globals',
            Kernel::Globals()
        );

        $this->assertEquals(
            $GLOBALS['_SERVER']['argv'][0],
            Kernel::Globals('_SERVER.argv.0')
        );
    }


    /**
     * EVENTのテスト
     */
    public function testEvent()
    {
        $this->assertInstanceOf(
            'Seaf\Kernel\Component\Event',
            Kernel::Event()
        );

        $cnt = 0;
        $e = Kernel::Event();
        $e->on('test', function()use(&$cnt){
            $cnt++;
        });
        for($i=0;$i<50;$i++) $e->trigger('test');

        $this->assertEquals(50, $cnt);
    }

    /**
     * モジュールローダのテスト
     */
    public function testModuleLoader()
    {
        $this->assertInstanceOf(
            'Seaf\Kernel\Component\ModuleLoader',
            Kernel::ModuleLoader()
        );
        Kernel::ModuleLoader()->load('p18n');

        $this->assertTrue(
            defined('P18N_LOADED')
        );
    }

    /**
     * コンフィグのテスト
     */
    public function testConfig()
    {
        $this->assertInstanceOf(
            'Seaf\Kernel\Component\Config',
            Kernel::Config()
        );

        $c = Kernel::Config();
        $c->load(SEAF_PATH.'/tests/etc/setting.yaml');
        $c->set('SEAF_PROJECT_ROOT', SEAF_PATH.'/tests');
        $this->assertEquals(
            SEAF_PATH.'/tests/var/tmp',
            $c->get('dirs.tmp')
        );

        $this->assertEquals(
            SEAF_PATH.'/tests/var/tmp',
            $c('dirs.tmp')
        );
    }

    /**
     * ロガーのテスト
     */
    public function testLogger()
    {
        $this->assertInstanceOf(
            'Seaf\Kernel\Component\Logger',
            Kernel::Logger()
        );
        $log = Kernel::Logger();
        $log->addWriter(array(
            'type' => 'echo'
        ));
        $log->debug('test '.__FILE__.' '.__LINE__, get_class($log));
    }

}
