<?php
namespace Seaf\Test;

use Seaf\Seaf;
use Seaf\Kernel\Kernel;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-12 at 22:59:30.
 */
class SeafWebTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Application
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        Kernel::Globals( )->set('SERVER', array(
            'REQUEST_URI'                 => '/',
            'HTTP_X_HTTP_METHOD_OVERRIDE' => 'POST',
            'REQUEST_METHOD'              => 'GET',
            'SCRIPT_NAME'                 => 'index.php',
            'PATH_INFO'                   => '/info/abc'
        ));
        Kernel::System( )->map('halt', function ($body) {
        });
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testRequestPathInfo ( )
    {
        $req = Seaf::Web()->request();
        Kernel::Globals( )->set('SERVER', array(
            'REQUEST_URI'                 => '/',
            'HTTP_X_HTTP_METHOD_OVERRIDE' => 'POST',
            'REQUEST_METHOD'              => 'GET',
            'SCRIPT_NAME'                 => 'index.php',
            'PATH_INFO'                   => '/info/abc'
        ));
        Kernel::Globals( )->set('REQUEST', array(
            '_method' => 'PUT'
        ));
        $req->initRequest();
        $this->assertEquals(
            '/info/abc',
            Seaf::Web()->request()->uri
        );
        $this->assertEquals(
            'index.php',
            Seaf::Web()->request()->base_uri
        );
        $this->assertEquals(
            'PUT',
            Seaf::Web()->request()->method
        );
    }

    public function testRequest ( )
    {
        $req = Seaf::Web()->request();
        Kernel::Globals( )->set('SERVER', array(
            'REQUEST_URI'                 => '/app/script',
            'SCRIPT_NAME'                 => '/app/index.php',
        ));
        Kernel::Globals( )->set('REQUEST', array());
        $req->initRequest();
        $this->assertEquals(
            '/script',
            Seaf::Web()->request()->uri
        );
        $this->assertEquals(
            '/app',
            Seaf::Web()->request()->base_uri
        );
        $this->assertEquals(
            'GET',
            Seaf::Web()->request()->method
        );
    }


    /**
     * Console Application
     */
    public function testConsoleApplication ( )
    {
        $req = Seaf::Web()->request();
        $web = Seaf::Web();
        $web->route('/', function ($req, $res) {
            echo '画面';
        })->route('/admin', function ($req, $res) {
            echo '管理画面';
        });


        $this->assertInstanceOf(
            'Seaf\Application\Web\Base',
            Seaf::Web()
        );

        $this->assertInstanceOf(
            'Seaf\Application\Web\Component\Request',
            Seaf::Web()->request()
        );

        Kernel::Globals( )->set('SERVER', array(
            'REQUEST_URI'                 => '/app/',
            'SCRIPT_NAME'                 => '/app/index.php',
        ));
        $req->initRequest();
        $web->run( );
        $this->assertEquals(
            '画面',
            $web->response()->body
        );

        Kernel::Globals( )->set('SERVER', array(
            'REQUEST_URI'                 => '/app/admin',
            'SCRIPT_NAME'                 => '/app/index.php',
        ));
        $req->initRequest();
        $web->response()->init();
        $web->run( );
        $this->assertEquals(
            '管理画面',
            $web->response()->body
        );

    }

}
