<?php
namespace Seaf\Core\Environment;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-11 at 20:18:34.
 */
class EnvironmentTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Environment
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Environment();
    }

    public function testDI()
    {
        $this->assertInstanceOf(
            'Seaf\Core\Environment\ComponentManager',
            $this->object->di()
        );

    }
}
