<?php
namespace Seaf\Environment;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-14 at 14:03:14.
 */
class EnvironmentTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Environment
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Environment;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testAutoComponentLoad()
    {
        $this->assertInstanceOf(
            'Seaf\Environment\Component\Logger',
            $this->object->logger()
        );
        $this->assertInstanceOf(
            'Seaf\Data\Config\Config',
            $this->object->config()
        );
    }

}
