<?php
namespace App;

use Seaf\Kernel\Kernel;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-13 at 02:44:03.
 */
class RootTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Root
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Root;
        Kernel::system()->map('halt',function(){});
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function testStory()
    {
        // アセットマネージャをマウントする
        $this->object->mount(
            '/assets','am'
        )->mount(
            '/admin','admin'
        );

        // アセットマネージャに渡るようにリクエストする
        $this->object->request('GET /assets/styles/app.css');
        ob_start();
        $this->object->run();
        $res = ob_get_clean();
        $this->assertTrue(strlen($res)>2000);

        // アドミンに渡るようにリクエストする
        $this->object->request('GET /admin/index');
        $this->object->response()->init();
        ob_start();
        $this->object->run();
        $res = ob_get_clean();
        $this->assertEquals(
            'yes',
            $this->object->response()->getParam('admin')
        );

        // 自分に渡るようにリクエストする
        $this->object->request('GET /index');
        $this->object->response()->init();
        $this->object->run();
        $this->assertEquals(
            'index',
            $this->object->response()->getParam('template')
        );

    }
}
