<?php
namespace Seaf\Config;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-11 at 10:05:56.
 */
class ConfigTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Config
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Config;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Seaf\Config\Config::set
     * @todo   Implement testSet().
     */
    public function testSet()
    {
        $this->object->loadArray($_SERVER);
        $this->object->argv->aaa->aaa->a = 'a';

        $this->assertEquals(
            'a',
            $this->object->get('argv.aaa.aaa.a')
        );
    }
}
