<?php
namespace Seaf\Environment;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-17 at 18:33:28.
 */
class BaseTest extends \PHPUnit_Framework_TestCase
{
    protected function setUp()
    {
        \Seaf\Kernel\Kernel::init();
        \Seaf\Kernel\Kernel::Logger()->addWriter(array(
            'type' => 'echo',
            'level' => 'ALL'
        ));
    }

    protected function tearDown()
    {
    }

    public function testInit()
    {
        $env = new Base();

        $this->assertInstanceOf(
            __NAMESPACE__.'\\Component\\Logger',
            $env->logger()
        );
        $this->assertInstanceOf(
            __NAMESPACE__.'\\Component\\Event',
            $env->event()
        );

        $env->map('test', function() {
            return true;
        });
        $env->map('test2', function() {
            echo 'hi';
        });
        $this->assertTrue($env->test());
        $env->on('test', function () {
            echo 'hi';
        });
        $env->on('test2', 'test2');

        ob_start();
        $env->trigger('test');
        $env->trigger('test2');
        $this->assertEquals(
            'hihi',
            ob_get_clean()
        );
    }
}
