<?php
namespace Seaf\Core\DI;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-10 at 20:46:42.
 */
class ContainerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Container
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Container;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Seaf\Core\DI\Container::register
     * @todo   Implement testRegister().
     */
    public function testRegister()
    {
        $this->object->register('object2', $this->object);
        $this->assertEquals(
            $this->object,
            $this->object->get('object2')
        );
        $this->object->register('factory', 'Seaf\Core\DI\Factory');
        $this->assertInstanceOf(
            'Seaf\Core\DI\Factory',
            $this->object->get('factory')
        );
    }

    /**
     * @covers Seaf\Core\DI\Container::has
     * @todo   Implement testHas().
     */
    public function testHas()
    {
        $this->object->register('object2', $this->object);
        $this->assertEquals(
            $this->object,
            $this->object->get('object2')
        );

        $this->assertTrue(
            $this->object->has('object2')
        );
    }
}
