<?php
namespace Seaf\Core\DI;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-10 at 19:38:24.
 */
class FactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Factory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = Factory::factory(array(
            'factory'=>array(
                'definition'=>'Seaf\Core\DI\Factory'
            )
        ));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Seaf\Core\DI\Factory::factory
     * @todo   Implement testFactory().
     */
    public function testFactory()
    {
        $object = $this->object;
        $factory = Factory::factory(array(
            'factory'=>array(
                'definition'=>'Seaf\Core\DI\Factory'
            ),
            'factory2'=>array(
                'definition' => function() use ($object){ return  $object; }
            )
        ));

        $this->assertInstanceOf(get_class($object), $factory->create('factory'));
        $this->assertEquals($object, $factory->create('factory2'));
    }

    /**
     * @covers Seaf\Core\DI\Factory::hasDefinition
     * @todo   Implement testHasDefinition().
     */
    public function testHasDefinition()
    {
        $this->assertTrue($this->object->hasDefinition('factory'));
    }

    /**
     * @covers Seaf\Core\DI\Factory::create
     * @todo   Implement testCreate().
     */
    public function testCreate()
    {
        $this->assertInstanceOf(
            get_class($this->object),
            $this->object->create('factory')
        );
    }
}
