<?php
namespace Seaf\Misc\AssetManager;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-11 at 06:19:17.
 */
class ApplicationTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Application
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Application;
        $this->object->fs()->addFilePath(
            '/assets',__DIR__.'/sample'
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Seaf\Misc\AssetManager\Application::catchAll
     * @todo   Implement testCatchAll().
     */
    public function testCatchAll()
    {
        $app = $this->object;
        $app->sys()->map('header',function($h){
            echo $h;
        });
        $app->sys()->map('halt',function($body=null){
            echo $body;
        });
        $app->request()->uri('/app.css');

        ob_start();
        $app->run();
        $css = ob_get_clean();

        $this->assertRegExp('/h1/',$css);
    }
}
