<?php
namespace Seaf\Application\Console;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-14 at 19:54:03.
 */
class BaseTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Base
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Base( );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Seaf\Application\Console\Base::initApplication
     */
    public function testInitApplication()
    {
        $base = $this->object;

        $this->assertInstanceOf(
            'Seaf\Application\Component\Request',
            $base->request()
        );

        $this->assertInstanceOf(
            'Seaf\Application\Component\Response',
            $base->response()
        );

        $this->assertInstanceOf(
            'Seaf\Application\Component\Router',
            $base->router()
        );
    }

    public function testRunApplication()
    {
        $base = $this->object;

        $result = false;

        $base->request('GET /');

        $base->route('/', function ( ) use (&$result) {
            $result = true;
        });

        $base->run();
    }
}
