<?php
namespace Seaf\Templator;

use Seaf\Core\Kernel;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-11 at 04:31:11.
 */
class PhpTemplatorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PhpTemplator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = Templator::factory(array(
            'type' => 'php',
            'dirs' => array('/template')
        ));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Seaf\Templator\PhpTemplator::render
     */
    public function testRender()
    {
        $this->assertInstanceOf(
            'Seaf\Templator\Templator',
            $this->object
        );

        Kernel::fs()->addFilePath('/template',__DIR__.'/sample');

        $this->assertEquals(
            '<h1>Hello World</h1>',
            trim(
                $this->object->render('/template/sample.php',array('title' => 'Hello World'))
            )
        );

    }
}
