<?php
namespace Seaf\Templator;

use Seaf\Core\Kernel;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-11 at 04:48:25.
 */
class TwigTemplatorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TwigTemplator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        Kernel::fs()->addFilePath('/template', __DIR__.'/sample');
        Kernel::fs()->addFilePath('/cache', '/tmp');
        $this->object = new TwigTemplator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Seaf\Templator\TwigTemplator::render
     */
    public function testRender()
    {
        $this->assertEquals(
            '<h1>HI</h1>',
            trim($this->object->render('sample.twig', array('title' =>'HI')))
        );
    }
}
