<?php // vim: set ft=php ts=4 sts=4 sw=4 et:

namespace Seaf\FW\Web;

use Seaf;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-26 at 03:27:37.
 */
class ControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Controller
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        Seaf::web()->initWeb();
        Seaf::system()->map('halt', function ($body) {
            echo $body;
        });
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testStandard ( )
    {
        Seaf::web()->route('/', function ( ) {
            echo 'hi';
        });
        Seaf::web()->run();
    }

    public function testMount ( )
    {
        $c = new Controller();
        $c->route('/', function ( ) {
            echo 'admin';
        });
        Seaf::web()->request('/admin');
        Seaf::web()->mount('/admin', $c);

        Seaf::web()->run();
    }

    public function testCompiler ( )
    {
        Seaf::web()
            ->register('compiler', 'Seaf\Util\Compiler\Compiler');

        Seaf::web()->route('/', function ($req, $res, $web) {
            //$web->compiler()->sass(Seaf::config('dirs.assets').'/styles/app.sass');
            //$web->compiler()->coffee(Seaf::config('dirs.assets').'/scripts/app.coffee');
        });

        Seaf::web()->run();
    }

    public function testView ( )
    {
        Seaf::web()->view()->enable()->layout(true);

        Seaf::web()->route('/', function ($req, $res, $web) {
            echo 'hi';
        });

        Seaf::web()->run();
    }
}
