<?php
namespace Seaf\Console;

use Seaf\Core\Kernel;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-11 at 02:52:48.
 */
class ApplicationTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Application
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        Kernel::init(array(
            'vars' => array(
                'argv' => array(
                    'index.php',
                    'hoge'
                )
            )
        ));
        $this->object = new Application;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Seaf\Console\Application::initApplication
     */
    public function testInitApplication()
    {
        $app = new Application();
        $this->assertEquals(
            'hoge',
            $app->request()->uri()
        );
    }

    /**
     * @covers Seaf\Console\Application::exec
     */
    public function testExec()
    {
        ob_start();
        $this->object->exec('echo "12345"');
        $this->assertRegExp('/12345/', trim(ob_get_clean()));
    }

    /**
     * @covers Seaf\Console\Application::out
     */
    public function testOut()
    {
        ob_start();
        $this->object->out('hi');
        $this->assertRegExp('/hi/', trim(ob_get_clean()));
    }

    /**
     * @covers Seaf\Console\Application::in
     */
    public function testIn()
    {
        ob_start();
        $this->object->in('y or n', 'y');
        $this->assertRegExp('/\[y\]/', trim(ob_get_clean()));
    }

    /**
     * @covers Seaf\Console\Application::_notfound
     */
    public function test_notfound()
    {
        ob_start();
        $this->object->notfound();
        $this->assertRegExp('/Usage/', trim(ob_get_clean()));
    }
}
