<?php // vim: set ft=php ts=4 sts=4 sw=4 et:

namespace Seaf\FW\Web;

use Seaf;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-26 at 03:27:37.
 */
class ControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Controller
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        Seaf::web()->initWeb();
        Seaf::system()->map('halt', function ($body) {
            echo $body;
        });
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testStandard ( )
    {
        Seaf::web()->route('/', function ( ) {
            echo 'hi';
        });
        ob_start();
        Seaf::web()->run();
        $this->assertEquals(
            'hi',
            ob_get_clean()
        );
    }

    public function testMount ( )
    {
        $c = new Controller();
        $c->route('/', function ( ) {
            echo 'admin';
        });
        Seaf::web()->request('/admin');
        Seaf::web()->mount('/admin', $c);

        ob_start();
        Seaf::web()->run();
        $this->assertEquals(
            'admin',
            ob_get_clean()
        );
    }

    public function testCompiler ( )
    {
        Seaf::web()
            ->register('compiler', 'Seaf\Util\Compiler\Compiler');

        Seaf::web()->route('/', function ($req, $res, $web) {
            $assetdir = Seaf::FileSystem(Seaf::Config('asset.dirs'));
            $web->compiler()->sass($assetdir->get('styles/app.sass'));
            $web->compiler()->coffee($assetdir->get('scripts/app.coffee'));
        });

        ob_start();
        Seaf::web()->run();
        $result = ob_get_clean();

        $this->assertRegexp(
            '/Generated/',
            $result
        );
        $this->assertRegexp(
            '/html/',
            $result
        );
    }

    public function testView ( )
    {
        Seaf::web()->view()->enable()->layout(true);

        Seaf::web()->route('/', function ($req, $res, $web) {
            echo 'hi';
        });

        ob_start();
        Seaf::web()->run();
        $result = ob_get_clean();

        $this->assertRegexp(
            '/<html>/',
            $result
        );
    }
}
